#ifndef SAVE_NATURES_H
#define SAVE_NATURES_H

#define SAVE_NATURES 25

enum save_nature_t {
    SAVE_NATURE_HARDY,
    SAVE_NATURE_LONELY,
    SAVE_NATURE_BRAVE,
    SAVE_NATURE_ADAMANT,
    SAVE_NATURE_NAUGHTY,
    SAVE_NATURE_BOLD,
    SAVE_NATURE_DOCILE,
    SAVE_NATURE_RELAXED,
    SAVE_NATURE_IMPISH,
    SAVE_NATURE_LAX,
    SAVE_NATURE_TIMID,
    SAVE_NATURE_HASTY,
    SAVE_NATURE_SERIOUS,
    SAVE_NATURE_JOLLY,
    SAVE_NATURE_NAIVE,
    SAVE_NATURE_MODEST,
    SAVE_NATURE_MILD,
    SAVE_NATURE_QUIET,
    SAVE_NATURE_BASHFUL,
    SAVE_NATURE_RASH,
    SAVE_NATURE_CALM,
    SAVE_NATURE_GENTLE,
    SAVE_NATURE_SASSY,
    SAVE_NATURE_CAREFUL,
    SAVE_NATURE_QUIRKY,
};

#endif /* _____ #ifndef SAVE_NATURES_H _____ */
